from typing import List
from ..core.types import Scene, SceneRisk, ProducerReport, BudgetPressure, ScheduleIssue, ScenarioResult

class ReportAdapter:
    def __init__(self, title: str = "CineSafe Production Analysis"):
        self.title = title

    def build_report(
        self,
        scenes: List[Scene],
        risks: List[SceneRisk],
        budget_pressures: List[BudgetPressure] = [],
        schedule_issues: List[ScheduleIssue] = [],
        scenario_results: List[ScenarioResult] = []
    ) -> ProducerReport:
        
        markdown = f"# {self.title}\n\n"
        
        # 1. Executive Summary
        markdown += "## 📊 Executive Summary\n"
        markdown += f"- **Total Scenes**: {len(scenes)}\n"
        avg_risk = sum(r.overall_risk_score for r in risks) / len(risks) if risks else 0
        markdown += f"- **Production Risk Profile**: {'🔴 High' if avg_risk > 6 else '🟡 Moderate' if avg_risk > 3 else '🟢 Low'} ({avg_risk:.1f}/10.0)\n"
        
        if scenario_results:
            markdown += f"- **Active Scenario**: {scenario_results[0].preset_name.replace('_', ' ').title()}\n"
            markdown += f"- **Scenario Impact**: {scenario_results[0].impact_summary}\n"
        markdown += "\n"

        # 2. Top Risks
        markdown += "## ⚠️ Critical Risks & Mitigations\n"
        sorted_risks = sorted(risks, key=lambda x: x.overall_risk_score, reverse=True)[:3]
        for r in sorted_risks:
            scene = next((s for s in scenes if s.scene_number == r.scene_number), None)
            if scene:
                markdown += f"### Scene {r.scene_number}: {scene.location}\n"
                markdown += f"**Risk Flags**: {', '.join(r.risk_flags)}\n"
                markdown += "**Mitigations**:\n"
                for m in r.mitigations[:2]:
                    markdown += f"- {m}\n"
                markdown += "\n"

        # 3. Budget Hotspots
        markdown += "## 💸 Budget Pressure Points\n"
        hotspots = sorted(budget_pressures, key=lambda x: x.complexity_score, reverse=True)[:3]
        for b in hotspots:
            markdown += f"- **Scene {b.scene_number}**: {b.pressure_band} Pressure (Score: {b.complexity_score})\n"
            markdown += f"  - Driver: {', '.join(b.cost_drivers)}\n"
        markdown += "\n"

        # 4. Schedule Warnings
        if schedule_issues:
            markdown += "## 📅 Schedule & Logistics\n"
            for issue in schedule_issues[:3]:
                markdown += f"### {issue.issue_type} ({issue.severity})\n"
                markdown += f"{issue.description}\n"
                markdown += f"**Recommendation**: {issue.recommendation}\n\n"

        # 5. Scenario Comparison
        if scenario_results:
            res = scenario_results[0]
            markdown += "## 🧪 Scenario Simulation Results\n"
            markdown += f"**Strategic Changes**:\n"
            for c in res.changes_applied:
                markdown += f"- {c}\n"
            markdown += f"**Tradeoffs**:\n"
            for t in res.tradeoffs:
                markdown += f"- {t}\n\n"

        markdown += "\n---\n*Generated by CineSafe Agent — Powered by Gemini 3.1 Flash-Preview*"

        return ProducerReport(
            title=self.title,
            project_summary="Comprehensive production feasibility analysis.",
            scene_count=len(scenes),
            top_risks=sorted_risks,
            top_budget_hotspots=hotspots,
            schedule_warnings=schedule_issues,
            scenario_results=scenario_results,
            markdown=markdown
        )

def build_report(scenes, risks, budget_pressures, schedule_issues, scenario_results):
    adapter = ReportAdapter()
    return adapter.build_report(scenes, risks, budget_pressures, schedule_issues, scenario_results)
